<?php

namespace ContainerKZ0xuws;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getFosElastica_IndexManagerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'fos_elastica.index_manager' shared service.
     *
     * @return \FOS\ElasticaBundle\Index\IndexManager
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/friendsofsymfony/elastica-bundle/src/Index/IndexManager.php';

        $a = ($container->services['FOS\\ElasticaBundle\\Elastica\\Index $books3Index'] ?? $container->load('getIndexbooks3IndexService'));

        if (isset($container->privates['fos_elastica.index_manager'])) {
            return $container->privates['fos_elastica.index_manager'];
        }

        return $container->privates['fos_elastica.index_manager'] = new \FOS\ElasticaBundle\Index\IndexManager(['books_3' => $a], $a);
    }
}
