<?php

namespace ContainerC1xCQav;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_IaxaOsYService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private '.service_locator.iaxaOsY' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.iaxaOsY'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'requestDto' => ['privates', 'App\\Request\\BookSearchContentRequest', 'getBookSearchContentRequestService', true],
        ], [
            'requestDto' => 'App\\Request\\BookSearchContentRequest',
        ]);
    }
}
