<?php

namespace ContainerC1xCQav;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_AYXsyWeService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private '.service_locator.AYXsyWe' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.AYXsyWe'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'App\\Controller\\BookSearchController::searchBookContent' => ['privates', '.service_locator.iaxaOsY', 'get_ServiceLocator_IaxaOsYService', true],
            'App\\Controller\\BookSearchController::searchBooks' => ['privates', '.service_locator.ILfGkSt', 'get_ServiceLocator_ILfGkStService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Controller\\BookSearchController:searchBookContent' => ['privates', '.service_locator.iaxaOsY', 'get_ServiceLocator_IaxaOsYService', true],
            'App\\Controller\\BookSearchController:searchBooks' => ['privates', '.service_locator.ILfGkSt', 'get_ServiceLocator_ILfGkStService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
        ], [
            'App\\Controller\\BookSearchController::searchBookContent' => '?',
            'App\\Controller\\BookSearchController::searchBooks' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'App\\Controller\\BookSearchController:searchBookContent' => '?',
            'App\\Controller\\BookSearchController:searchBooks' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
        ]);
    }
}
