<?php

namespace ContainerC1xCQav;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getBookSearchRequestService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'App\Request\BookSearchRequest' shared autowired service.
     *
     * @return \App\Request\BookSearchRequest
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service "App\\Request\\BookSearchRequest": argument "$searchQuery" of method "__construct()" has no type-hint, you should configure its value explicitly.');
    }
}
