<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerKZ0xuws\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerKZ0xuws/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerKZ0xuws.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerKZ0xuws\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerKZ0xuws\App_KernelDevDebugContainer([
    'container.build_hash' => 'KZ0xuws',
    'container.build_id' => '1bd0b925',
    'container.build_time' => 1744725916,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerKZ0xuws');
