<?php

namespace ContainerXKnaxtC;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_ILfGkStService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private '.service_locator.ILfGkSt' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.ILfGkSt'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'requestDto' => ['privates', 'App\\Request\\BookSearchRequest', NULL, 'Cannot autowire service "App\\Request\\BookSearchRequest": argument "$searchQuery" of method "__construct()" is type-hinted "string", you should configure its value explicitly.'],
        ], [
            'requestDto' => 'App\\Request\\BookSearchRequest',
        ]);
    }
}
