<?php

namespace ContainerXKnaxtC;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getBookSearchContentRequestService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'App\Request\BookSearchContentRequest' shared autowired service.
     *
     * @return \App\Request\BookSearchContentRequest
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Contract/Request/TransformableToDTO.php';
        include_once \dirname(__DIR__, 4).'/src/Request/BookSearchContentRequest.php';

        return $container->privates['App\\Request\\BookSearchContentRequest'] = new \App\Request\BookSearchContentRequest();
    }
}
