<?php

namespace ContainerXKnaxtC;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getIndexbooks3IndexService extends App_KernelTestDebugContainer
{
    /**
     * Gets the public 'FOS\ElasticaBundle\Elastica\Index $books3Index' shared service.
     *
     * @return \FOS\ElasticaBundle\Elastica\Index
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/ruflin/elastica/src/SearchableInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/ruflin/elastica/src/Index.php';
        include_once \dirname(__DIR__, 4).'/vendor/friendsofsymfony/elastica-bundle/src/Elastica/Index.php';

        $a = ($container->privates['fos_elastica.client.default'] ?? $container->load('getFosElastica_Client_DefaultService'));

        if (isset($container->services['FOS\\ElasticaBundle\\Elastica\\Index $books3Index'])) {
            return $container->services['FOS\\ElasticaBundle\\Elastica\\Index $books3Index'];
        }

        return $container->services['FOS\\ElasticaBundle\\Elastica\\Index $books3Index'] = $a->getIndex('books_3');
    }
}
