<?php

namespace ContainerXKnaxtC;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSecurityServiceService extends App_KernelTestDebugContainer
{
    /**
     * Gets the public 'App\Service\SecurityService' shared autowired service.
     *
     * @return \App\Service\SecurityService
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Contract/Service/SecurityServiceInterface.php';
        include_once \dirname(__DIR__, 4).'/src/Service/SecurityService.php';

        $container->services['App\\Service\\SecurityService'] = $instance = new \App\Service\SecurityService();

        $instance->login();

        return $instance;
    }
}
