# config/packages/prod/fos_elastica.yaml
fos_elastica:
  clients:
    default:
      connections:
        - url: 'https://192.168.17.14:9200'
          username: '%env(ELASTICSEARCH_USER)%'
          password: '%env(ELASTICSEARCH_PASSWORD)%'
          curl:
            64: false
            81: false

        - url: 'https://192.168.17.13:9200'
          username: '%env(ELASTICSEARCH_USER)%'
          password: '%env(ELASTICSEARCH_PASSWORD)%'
          curl:
            64: false
            81: false

        - url: 'https://192.168.17.12:9200'
          username: '%env(ELASTICSEARCH_USER)%'
          password: '%env(ELASTICSEARCH_PASSWORD)%'
          curl:
            64: false
            81: false
  serializer: ~
  indexes:
    books_3:
      properties:
        book_id:
          type: integer
        book_name:
          type: text
          analyzer: standard