<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXKnaxtC\App_KernelTestDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXKnaxtC/App_KernelTestDebugContainer.php') {
    touch(__DIR__.'/ContainerXKnaxtC.legacy');

    return;
}

if (!\class_exists(App_KernelTestDebugContainer::class, false)) {
    \class_alias(\ContainerXKnaxtC\App_KernelTestDebugContainer::class, App_KernelTestDebugContainer::class, false);
}

return new \ContainerXKnaxtC\App_KernelTestDebugContainer([
    'container.build_hash' => 'XKnaxtC',
    'container.build_id' => '331c1992',
    'container.build_time' => 1744973230,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXKnaxtC');
